### ISSUE TITLE
[USECASE] L'utilisateur souhaite visualiser la requête avec un Tree Map

### ISSUE THREAD

**Issue by Sensaku** [Sensaku/sparql_lib#2]

**Comment by Sensaku** [comment]
Related task:
- [ ] Trouver des requêtes types SPARQL (4 - 5 dans l'idéal) #9 
- [ ] Définir la fonction de transformation des données d'entrée en données utilisable pour le Tree Map #10 
- [ ] Définir les différents paramètres possibles pour personnaliser l'affichage des Tree Map #11 
- [ ] Faire la documentation de l'utilisation du code Javascript "classique" (fonction based) #12 
- [ ] Faire la documentation de l'utilisation du code Javascript "Component Based" #13 
- [ ] Faire la documentation de l'utilisation du code Javascript "React Based" #14
